package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/base.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>南京艾派克斯TOM工作室 APEXTOM-WORKSHOP</title>\r\n");
      out.write('\n');

String basePath = request.getContextPath();
String  path= request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+basePath;

      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/scripts/themes/default/easyui.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/scripts/themes/icon.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/jquery.easyui.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/easyui-lang-zh_CN.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/jquery.dropdown.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/jquery.easing.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/common.function.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/scripts/general.function.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/common.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/style.css\">");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("<meta content=\"南京艾派克斯\" name=\"keywords\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"APEX,TOM,APEXTOM,WORKSHOP,南京艾派克斯,教育,遥遥领先行业对手!\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/img/apextom.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<base href=\"");
      out.print(path );
      out.write("\" target=\"_self\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar old_cur = parseInt(\"2\");\r\n");
      out.write("\tvar cur = old_cur;\r\n");
      out.write("\tjQuery(document).ready(function() {\r\n");
      out.write("\t\tif (old_cur > 0) {\r\n");
      out.write("\t\t\tjQuery('#smoth_block').css({\r\n");
      out.write("\t\t\t\tleft : jQuery('#nav a[top=' + old_cur + ']').offset().left,\r\n");
      out.write("\t\t\t\ttop : 163\r\n");
      out.write("\t\t\t}).show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tjQuery('#nav a').hover(function(event) {//hover\r\n");
      out.write("\t\t\tif (jQuery(this).attr('top') != cur) {\r\n");
      out.write("\t\t\t\tjQuery('#smoth_block').stop();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar left = jQuery(this).offset().left;\r\n");
      out.write("\t\t\t\tvar top = jQuery(this).offset().top;\r\n");
      out.write("\t\t\t\tcur = jQuery(this).attr('top');\r\n");
      out.write("\t\t\t\tjQuery('#smoth_block').animate({\r\n");
      out.write("\t\t\t\t\tleft : left,\r\n");
      out.write("\t\t\t\t\ttop : top\r\n");
      out.write("\t\t\t\t}, 500, 'backout').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tjQuery('.content_top').mouseover(function() {\r\n");
      out.write("\t\t\tif (old_cur > 0) {\r\n");
      out.write("\t\t\t\tjQuery('#smoth_block').stop();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar left = jQuery('#nav a[top=' + old_cur + ']').offset().left;\r\n");
      out.write("\t\t\t\tvar top = jQuery('#nav a[top=' + old_cur + ']').offset().top;\r\n");
      out.write("\t\t\t\tcur = old_cur;\r\n");
      out.write("\t\t\t\tjQuery('#smoth_block').animate({\r\n");
      out.write("\t\t\t\t\tleft : left,\r\n");
      out.write("\t\t\t\t\ttop : top\r\n");
      out.write("\t\t\t\t}, 500, 'backout').show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//Gray\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"all\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(document)\r\n");
      out.write("\t\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery('.dropdown_contact')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.mouseover(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.setDropDown(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery('.dropdown_contact_sub'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery(\"#fxbtn\").mouseover(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tjQuery('.cate_1').mouseover(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjQuery('.cate_1').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}).mouseout(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjQuery('.cate_1').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\tjQuery('.cate_1').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t}).mouseout(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tjQuery('.cate_1').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar js = new JsLoader();\r\n");
      out.write("\t\t\t\t\t\t\t\tjs.load('http://v2.jiathis.com/code/jia.js');\r\n");
      out.write("\t\t\t\t\t\t\t\tjs.onsuccess = function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//jQuery('#ckepop').show() ;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tjs.onfailure = function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//jQuery('#ckepop').hide() ;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t//客服\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery(\".kf_info\").css('width', '0')\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery(\".kf_btn\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.mouseover(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif (jQuery(\".kf_info\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'width') == '0px') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery(\".kf_info\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.animate({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth : 175\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}, \"slow\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery('.kf_btn img')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.attr('src',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'");
      out.print(path);
      out.write("/img/kf_btn01.png')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tjQuery('.kf_info')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.mouseleave(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif (jQuery(\".kf_info\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'width') == '175px') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery(\".kf_info\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.animate({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth : 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}, \"slow\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery('.kf_btn img')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.attr('src',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'");
      out.print(path);
      out.write("/img/kf_btn02.png')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"position: absolute; width: 122px; height: 54px; background-image: url(");
      out.print(path);
      out.write("/img/index12.gif); z-index: 0; left: 1127px; top: 163px; background-position: initial initial; background-repeat: no-repeat no-repeat;\"\r\n");
      out.write("\t\t\tid=\"smoth_block\"></div>\r\n");
      out.write("\t\t<div class=\"header\" id=\"nav_header\" style=\"position: relative;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- JiaThis Button BEGIN -->\r\n");
      out.write("\t\t\t<div id=\"ckepop\" class=\"cate_1\" parentvalue=\"1\"\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; right: -23px; top: 50px; background-image: url(");
      out.print(path);
      out.write("/img/fx_bj.png); width: 112px; height: 20px; padding-left: 60px; padding-top: 15px; display: none;\">\r\n");
      out.write("\t\t\t\t<a class=\"jiathis_button_qzone\" title=\"分享到QQ空间\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_txt jtico jtico_qzone\"></span></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_button_tsina\" title=\"分享到新浪微博\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_txt jtico jtico_tsina\"></span></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_button_tqq\" title=\"分享到腾讯微博\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_txt jtico jtico_tqq\"></span></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_button_renren\" title=\"分享到人人网\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_txt jtico jtico_renren\"></span></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_button_taobao\" title=\"分享到淘江湖\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"jiathis_txt jtico jtico_taobao\"></span></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- JiaThis Button END -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"http://www.bingoidea.net\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(path);
      out.write("/img/logo.png\" border=\"0\"></a> <a\r\n");
      out.write("\t\t\t\t\thref=\"http://apextom.com\" target=\"_blank\" class=\"outlin\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(path);
      out.write("/img/logo_btn.png\" width=\"32\" height=\"32\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"contact\">\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(path);
      out.write("/img/tel.gif\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t\t<!-- WPA Button Begin -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- WPA Button END -->\r\n");
      out.write("\t\t\t\t<a id=\"fxbtn\" href=\"javascript:\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(path);
      out.write("/img/fx.gif\" style=\"border: none;\" alt=\"分享\"></a>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 20px; padding-right: 10px; padding-left: 300px; display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_contact\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"contact_us.html\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #fff; text-decoration: none;\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(path);
      out.write("/img/dropdown.png\" hspace=\"5\" border=\"0\">联系</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown_contact_sub\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"contact_us.html?type=taiyuan\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #fff; text-decoration: none;\">联系</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"all_link\" id=\"nav\">\r\n");
      out.write("\t\t\t\t<a href=\"http://www.bingoidea.net\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-left: 70px; _margin-left: 30px;\" top=\"1\">缤果首页<br>\r\n");
      out.write("\t\t\t\t<font>Home</font></a> <a href=\"about_us.html\" top=\"2\">关于缤果<br>\r\n");
      out.write("\t\t\t\t<font>AboutUs</font></a> <a href=\"case.html\" top=\"3\">缤果案例<br>\r\n");
      out.write("\t\t\t\t<font>OurCase</font></a> <a href=\"service.html\" top=\"4\">缤果服务<br>\r\n");
      out.write("\t\t\t\t<font>OurService</font></a> <a href=\"contact_us.html\" top=\"5\">联系缤果<br>\r\n");
      out.write("\t\t\t\t<font>ContactUs</font></a> <a href=\"http://www.bingoidea.net/flash\"\r\n");
      out.write("\t\t\t\t\ttop=\"6\">Flash版<br>\r\n");
      out.write("\t\t\t\t<font>Flash</font></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 100%; background: #000; position: absolute; left: 0px; top: 0px; z-index: 100000; display: none;\"\r\n");
      out.write("\t\t\tid=\"mask_loading\"></div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 100%; position: absolute; left: 0px; top: 0px; z-index: 100001; display: none; text-align: center; color: #fff;\"\r\n");
      out.write("\t\t\tid=\"text_loading\">正在加载数据...</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--客服-->\r\n");
      out.write("\t\t<div class=\"kf\">\r\n");
      out.write("\t\t\t<div class=\"kf_info\" style=\"width: 0px;\">\r\n");
      out.write("\t\t\t\t<div style=\"padding-left: 8px;\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(path);
      out.write("/img/kf_phone.jpg\" width=\"158\" height=\"27\">\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"context\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"tencent://message/?uin=&amp;Site=cherry&amp;Menu=yes\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Bingo.Jimmy</strong><br> Tel: 186-1682-7767\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"kf_btn\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(path);
      out.write("/img/kf_btn02.png\" width=\"32\" height=\"194\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--客服-->\r\n");
      out.write("\t\t<div class=\"content_top\">\r\n");
      out.write("\t\t\t<div class=\"aboutus_left\">\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tvar left = parseInt(\"2\");\r\n");
      out.write("\t\t\t\t\tjQuery(document)\r\n");
      out.write("\t\t\t\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjQuery('#left_nav a')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (jQuery(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.attr(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'left') == left) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tjQuery(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'border-left',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'#99cc00 10px solid');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div id=\"left_nav\">\r\n");
      out.write("\t\t\t\t\t<a class=\"one\" href=\"opinion.html\" left=\"1\"></a> <a class=\"two\"\r\n");
      out.write("\t\t\t\t\t\thref=\"about_us.html\" left=\"2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-left-color: rgb(153, 204, 0); border-left-width: 10px; border-left-style: solid;\"></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"three\" href=\"news_show.html\" left=\"3\"></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"four\" href=\"join_us.html\" left=\"4\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"aboutus_right\">\r\n");
      out.write("\t\t\t\t<p class=\"picone\">\r\n");
      out.write("\t\t\t\t\t<span class=\"aboutus_font\" style=\"color: #99cc00\">&nbsp;&nbsp;&nbsp;“缤果创意”</span>隶属于上海<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"aboutus_font\" style=\"color: #99cc01\">思壤信息技术</span>有限公司。\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"pictwo\">\r\n");
      out.write("\t\t\t\t\t<span class=\"aboutus_font\" style=\"color: #ff8c00\">&nbsp;&nbsp;&nbsp;“缤果创意”</span>BINGOIDEA专注于<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"aboutus_font\" style=\"color: #ff8c00\">网站建设</a>，依靠专业网站建设技术致力于系统化解决您的企业品牌在互联网上的统一性传播。从<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"aboutus_font\" style=\"color: #ff8c00\">网站咨询策划、界面设计、交互设计，线上营销策划到网站程序开发、网站视觉整合，</a>我们都提供适合您需求的一站式专业建站方案。\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"picthree\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: #0099cc\">&nbsp;&nbsp;&nbsp;“缤果创意”</span>BINGOIDEA是（缤纷、果实、创意、智慧）的象征。“缤果创意”致力于成为在创意产业中囊括<a>平面设计、网站设计、网络推广、专业品牌设计等服务的专业互联网技术服务提供商。我们奉行</a><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"aboutus_font\" style=\"color: #0099cc\">“<span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #0099cc\">设</span>计彰显品质,创意改变生活”\r\n");
      out.write("\t\t\t\t\t</a>的宗旨，以准确的市场定位和客户的需求为目的，拥有着热情、细致、专注的高素质团队，更具魅力的是他们拥有非凡的创造力和无私的奉献精神。我们一直秉承国际化、品牌化的创作理念和规范专业的设计态度，创造力与专注度决定了我们能胜任一切挑战。\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"picfour\">\r\n");
      out.write("\t\t\t\t\t<a class=\"aboutus_font\" style=\"color: #376092\">&nbsp;&nbsp;&nbsp;“缤果创意”\r\n");
      out.write("\t\t\t\t\t</a>是朝气蓬勃、积极创造的<a class=\"aboutus_font\" style=\"color: #376092\">风向</a>；<br>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;<a class=\"aboutus_font\" style=\"color: #376092\">“缤果创意”\r\n");
      out.write("\t\t\t\t\t</a>将是专业化、规范化的<a class=\"aboutus_font\" style=\"color: #376092\">标尺</a>；<br>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;<a class=\"aboutus_font\" style=\"color: #376092\">“缤果创意”\r\n");
      out.write("\t\t\t\t\t</a>会是互联网技术服务领域的<a class=\"aboutus_font\" style=\"color: #376092\">典范</a>。\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\" class=\"aboutusbj\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content_bot\"></div>\r\n");
      out.write("\t\t﻿\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<a href=\"http://www.bingoidea.net\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-left: 200px; _margin-left: 100px;\" class=\"footermenu\">Home</a>\r\n");
      out.write("\t\t\t<a href=\"http://www.bingoidea.net/blog\" class=\"footermenu\">Blog</a> <a\r\n");
      out.write("\t\t\t\thref=\"contact_us.html\" class=\"footermenu\">ContactUS</a> <a\r\n");
      out.write("\t\t\t\thref=\"sitemap.html\" class=\"footermenu\">SiteMap</a>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div style=\"padding: 0px;\">\r\n");
      out.write("\t\t\t\t\t友情链接:&nbsp;<a href=\"http://www.bingoidea.net/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-right: 10px;\">上海网站建设</a><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.bingoidea.net/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-right: 10px;\">网页设计</a><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.bingoidea.net/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-right: 10px;\">品牌网站设计</a><a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.bingoidea.net/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-right: 10px;\">高端网站建设</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t地址：上海市徐汇区石龙路345弄23-27号A座208 联系电话：+86-21-64681909<br> Copyright<font\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: Arial\">©</font>&nbsp;2009上海思壤信息技术有限公司 版权所有<br>\r\n");
      out.write("\t\t\t\t<a href=\"http://www.miibeian.gov.cn\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\trel=\"”nofollow”\">沪ICP备09089012号</a>&nbsp;\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3F7697c00db8641c0aa939f12b95728799' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\" http://hm.baidu.com/h.js?7697c00db8641c0aa939f12b95728799\"\r\n");
      out.write("\t\t\t\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\thref=\"http://www.sgs.gov.cn/lz/licenseLink.do?method=licenceView&amp;entyId=20120315163548399\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(path);
      out.write("/img/icon.gif\" width=\"47\" height=\"47\" border=\"0\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
